# Generated by Django 3.2.9 on 2021-12-03 08:17

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('vat', models.CharField(max_length=255, verbose_name='Vaše IČO')),
                ('capacity', models.IntegerField(default=10, help_text='Zadejte počet vakcinací, které za týden zvládnete', verbose_name='Kapacita')),
                ('day_monday', models.BooleanField(default=True, verbose_name='Pondělí')),
                ('day_tuesday', models.BooleanField(default=True, verbose_name='Úterý')),
                ('day_wednesday', models.BooleanField(default=True, verbose_name='Středa')),
                ('day_thursday', models.BooleanField(default=True, verbose_name='Čtvrtek')),
                ('day_friday', models.BooleanField(default=True, verbose_name='Pátek')),
                ('day_sathurday', models.BooleanField(default=False, verbose_name='Sobota')),
                ('day_sunday', models.BooleanField(default=False, verbose_name='Neděle')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefonní kontakt')),
            ],
            options={
                'verbose_name': 'Ordinace',
                'verbose_name_plural': 'Ordinace',
            },
        ),
    ]
