---
version: '2'

services:
  app:
    container_name: app
    image: msgre/liska:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $PWD:/app
    environment:
      PYTHONUNBUFFERED: 1
      DJANGO_DEBUG: "True"
      ALLOWED_HOSTS: "app,app:8088,app:8089,0.0.0.0,0.0.0.0:8088,0.0.0.0:8089,localhost,localhost:8088,localhost:8089"
      DATABASE_URL: "postgres://liska:pw@db:5432/liska"
      DATABASE_SSL_OFF: "True"
    ports:
      - "8088:8088"
      - "8089:8089"
    stop_signal: SIGINT
    working_dir: /app
    command: ./manage.py runserver app:8088
    links:
      - db
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: pw
      POSTGRES_USER: liska
      POSTGRES_DB: liska
