# Generated by Django 3.2.9 on 2021-12-03 09:39

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('first_name', models.CharField(max_length=255, verbose_name='Jméno')),
                ('last_name', models.CharField(max_length=255, verbose_name='Příjmení')),
                ('competence', models.CharField(choices=[('lekar', 'Lékař'), ('dobrovolnik_nezdravotnik', 'Dobrovolník nezdravotník')], default='', max_length=50, verbose_name='Kompetence')),
                ('region', models.CharField(choices=[('PHA', 'Hlavní město Praha'), ('STC', 'Středočeský kraj'), ('JHC', 'Jihočeský kraj'), ('PLK', 'Plzeňský kraj'), ('KVK', 'Karlovarský kraj'), ('ULK', 'Ústecký kraj'), ('LBK', 'Liberecký kraj'), ('HKK', 'Královéhradecký kraj'), ('PAK', 'Pardubický kraj'), ('VYS', 'Kraj Vysočina'), ('JHM', 'Jihomoravský kraj'), ('OLK', 'Olomoucký kraj'), ('MSK', 'Moravskoslezský kraj'), ('ZLK', 'Zlínský kraj')], max_length=100, verbose_name='Kraj')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Mobil')),
            ],
            options={
                'verbose_name': 'Existujicí místo',
                'verbose_name_plural': 'Existujicí místa',
            },
        ),
    ]
